### ISSUE TITLE
Updating location of mints alters mint search results, but not find search

### ISSUE THREAD

**Issue by pyzmark** [leemordechai/FLAME#27]
See attached video

https://user-images.githubusercontent.com/28210739/136853535-8731be10-57d3-4f9b-ab7c-3de60fbedccd.mp4

**Comment by leemordechai** [comment]
This particular case was resolved - maybe it updated automatically as some routine edit. I raised to the developer anyway.

**Comment by leemordechai** [comment]
The problem here seems to be an issue with the browser cache - that saved the old search and re-displays it instead of re-sending the request to the server. If you use a different browser/computer for the same search at the same time you should see the correct, updated location. For me the issue (not updating) was only on Chrome but when I used Firefox at the same time it gave me the correct location. 

All in all it'd be a minor issue that would affect only one person & the finds they have immediately edited. So there's nothing really to do on the code side but we could add a few lines to the contributor FAQ to call attention to this issue. 

@pyzmark please test & comment or close this issue

**Comment by leemordechai** [comment]
PS - on Chrome you can clear your cache by hitting F12, then go to the browser Chrome window, right-click on the refresh button and select 'Empty cache and hard reload'.

**Comment by leemordechai** [comment]
@pyzmark can you please check & close this?

**Comment by pyzmark** [comment]
Still can't test this as mint locations cannot be updated, per https://github.com/leemordechai/FLAME/issues/59

**Comment by leemordechai** [comment]
fixed, closing
![image](https://github.com/leemordechai/FLAME/assets/16713928/8590ca8c-5ba7-4e63-bbdf-cd200af81627)
